### ISSUE TITLE
5/5 Problem

### ISSUE THREAD

**Issue by alexofalger2026** [TheGamerDog/PluTail#3]
Hi brother thanks for sharing the game files I have tried but I don't have enough ability to run the game and I stayed stuck from 5/5 I will send you a log you can check it and I hope to find an answer from you on the shortest time I am waiting for you
![654354](https://github.com/user-attachments/assets/e186a234-09a5-4caa-a3b5-000b000c9e57)
the log 
PS D:\PLUFIRE AND PLUTAIL\PluTail-main\PluTail-main> java -jar PluTail.jar 
18:33:59 [main] INFO  PluTail - Let's pluck the tail of this fox!
18:33:59 [main] INFO  PluTail - Version: 0.0.1
18:33:59 [main] INFO  PluTail - Root path: D:\PLUFIRE AND PLUTAIL\PluTail-main\PluTail-main
18:33:59 [main] INFO  [Koin] - Started 7 definitions in 1.0382 ms
18:33:59 [main] INFO  PluTail - Loading PluTail...
18:34:00 [main] INFO  org.reflections.Reflections - Reflections took 192 ms to scan 1 urls, producing 14 keys and 111 values
18:34:00 [main] DEBUG PluTail - Discovered command handler: sys::Login -> ru.thegamerdog.plutail.command.handler.AuthHandler::login
18:34:00 [main] DEBUG PluTail - Discovered command handler: sys::VerCheck -> ru.thegamerdog.plutail.command.handler.AuthHandler::verCheck
18:34:00 [main] DEBUG PluTail - Registered command handler: AuthHandler
18:34:00 [main] DEBUG PluTail - Discovered command handler: sys::GetRoomList -> ru.thegamerdog.plutail.command.handler.RoomHandler::getRoomList
18:34:00 [main] DEBUG PluTail - Registered command handler: RoomHandler
18:34:00 [main] DEBUG PluTail - Discovered command handler: sys::SetUserVars -> ru.thegamerdog.plutail.command.handler.UVarsHandler::setUserVars
18:34:00 [main] DEBUG PluTail - Registered command handler: UVarsHandler
18:34:00 [main] DEBUG PluTail - Discovered command handler: sys::PublicMessage -> ru.thegamerdog.plutail.command.handler.MessageHandler::sendPublicMessage
18:34:00 [main] DEBUG PluTail - Registered command handler: MessageHandler
18:34:00 [main] INFO  PluTail - Zone  TweegeeWorldsRU  started
18:34:02 [main] INFO  PluTail - Started TCP server
18:34:09 [nioEventLoopGroup-3-1] INFO  PluTail - Socket accepted: /127.0.0.1:57528
18:34:09 [nioEventLoopGroup-3-1] INFO  PluTail - Socket disconnected: /127.0.0.1:57528
18:34:09 [nioEventLoopGroup-3-2] INFO  PluTail - Socket accepted: /127.0.0.1:57529

**Comment by TheGamerDog** [comment]
The instructions describe everything in as much detail as possible, re-read.
